# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bbrc', [dirname(__file__)])
        except ImportError:
            import _bbrc
            return _bbrc
        if fp is not None:
            try:
                _mod = imp.load_module('_bbrc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _bbrc = swig_import_helper()
    del swig_import_helper
else:
    import _bbrc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _bbrc.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _bbrc.SwigPyIterator_value(self)
    def incr(self, n = 1): return _bbrc.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _bbrc.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _bbrc.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _bbrc.SwigPyIterator_equal(self, *args)
    def copy(self): return _bbrc.SwigPyIterator_copy(self)
    def next(self): return _bbrc.SwigPyIterator_next(self)
    def __next__(self): return _bbrc.SwigPyIterator___next__(self)
    def previous(self): return _bbrc.SwigPyIterator_previous(self)
    def advance(self, *args): return _bbrc.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _bbrc.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _bbrc.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _bbrc.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _bbrc.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _bbrc.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _bbrc.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _bbrc.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class SVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _bbrc.SVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _bbrc.SVector___nonzero__(self)
    def __bool__(self): return _bbrc.SVector___bool__(self)
    def __len__(self): return _bbrc.SVector___len__(self)
    def pop(self): return _bbrc.SVector_pop(self)
    def __getslice__(self, *args): return _bbrc.SVector___getslice__(self, *args)
    def __setslice__(self, *args): return _bbrc.SVector___setslice__(self, *args)
    def __delslice__(self, *args): return _bbrc.SVector___delslice__(self, *args)
    def __delitem__(self, *args): return _bbrc.SVector___delitem__(self, *args)
    def __getitem__(self, *args): return _bbrc.SVector___getitem__(self, *args)
    def __setitem__(self, *args): return _bbrc.SVector___setitem__(self, *args)
    def append(self, *args): return _bbrc.SVector_append(self, *args)
    def empty(self): return _bbrc.SVector_empty(self)
    def size(self): return _bbrc.SVector_size(self)
    def clear(self): return _bbrc.SVector_clear(self)
    def swap(self, *args): return _bbrc.SVector_swap(self, *args)
    def get_allocator(self): return _bbrc.SVector_get_allocator(self)
    def begin(self): return _bbrc.SVector_begin(self)
    def end(self): return _bbrc.SVector_end(self)
    def rbegin(self): return _bbrc.SVector_rbegin(self)
    def rend(self): return _bbrc.SVector_rend(self)
    def pop_back(self): return _bbrc.SVector_pop_back(self)
    def erase(self, *args): return _bbrc.SVector_erase(self, *args)
    def __init__(self, *args): 
        this = _bbrc.new_SVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _bbrc.SVector_push_back(self, *args)
    def front(self): return _bbrc.SVector_front(self)
    def back(self): return _bbrc.SVector_back(self)
    def assign(self, *args): return _bbrc.SVector_assign(self, *args)
    def resize(self, *args): return _bbrc.SVector_resize(self, *args)
    def insert(self, *args): return _bbrc.SVector_insert(self, *args)
    def reserve(self, *args): return _bbrc.SVector_reserve(self, *args)
    def capacity(self): return _bbrc.SVector_capacity(self)
    __swig_destroy__ = _bbrc.delete_SVector
    __del__ = lambda self : None;
SVector_swigregister = _bbrc.SVector_swigregister
SVector_swigregister(SVector)

class Bbrc(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Bbrc, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Bbrc, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _bbrc.new_Bbrc(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _bbrc.delete_Bbrc
    __del__ = lambda self : None;
    def Reset(self): return _bbrc.Bbrc_Reset(self)
    def Defaults(self): return _bbrc.Bbrc_Defaults(self)
    def GetMinfreq(self): return _bbrc.Bbrc_GetMinfreq(self)
    def GetType(self): return _bbrc.Bbrc_GetType(self)
    def GetBackbone(self): return _bbrc.Bbrc_GetBackbone(self)
    def GetDynamicUpperBound(self): return _bbrc.Bbrc_GetDynamicUpperBound(self)
    def GetPruning(self): return _bbrc.Bbrc_GetPruning(self)
    def GetConsoleOut(self): return _bbrc.Bbrc_GetConsoleOut(self)
    def GetAromatic(self): return _bbrc.Bbrc_GetAromatic(self)
    def GetRefineSingles(self): return _bbrc.Bbrc_GetRefineSingles(self)
    def GetDoOutput(self): return _bbrc.Bbrc_GetDoOutput(self)
    def GetBbrcSep(self): return _bbrc.Bbrc_GetBbrcSep(self)
    def GetChisqActive(self): return _bbrc.Bbrc_GetChisqActive(self)
    def GetChisqSig(self): return _bbrc.Bbrc_GetChisqSig(self)
    def GetRegression(self): return _bbrc.Bbrc_GetRegression(self)
    def SetMinfreq(self, *args): return _bbrc.Bbrc_SetMinfreq(self, *args)
    def SetType(self, *args): return _bbrc.Bbrc_SetType(self, *args)
    def SetBackbone(self, *args): return _bbrc.Bbrc_SetBackbone(self, *args)
    def SetDynamicUpperBound(self, *args): return _bbrc.Bbrc_SetDynamicUpperBound(self, *args)
    def SetPruning(self, *args): return _bbrc.Bbrc_SetPruning(self, *args)
    def SetConsoleOut(self, *args): return _bbrc.Bbrc_SetConsoleOut(self, *args)
    def SetAromatic(self, *args): return _bbrc.Bbrc_SetAromatic(self, *args)
    def SetRefineSingles(self, *args): return _bbrc.Bbrc_SetRefineSingles(self, *args)
    def SetDoOutput(self, *args): return _bbrc.Bbrc_SetDoOutput(self, *args)
    def SetBbrcSep(self, *args): return _bbrc.Bbrc_SetBbrcSep(self, *args)
    def SetChisqActive(self, *args): return _bbrc.Bbrc_SetChisqActive(self, *args)
    def SetChisqSig(self, *args): return _bbrc.Bbrc_SetChisqSig(self, *args)
    def SetRegression(self, *args): return _bbrc.Bbrc_SetRegression(self, *args)
    def SetMaxHops(self, *args): return _bbrc.Bbrc_SetMaxHops(self, *args)
    def MineRoot(self, *args): return _bbrc.Bbrc_MineRoot(self, *args)
    def ReadGsp(self, *args): return _bbrc.Bbrc_ReadGsp(self, *args)
    def AddCompound(self, *args): return _bbrc.Bbrc_AddCompound(self, *args)
    def AddActivity(self, *args): return _bbrc.Bbrc_AddActivity(self, *args)
    def GetNoRootNodes(self): return _bbrc.Bbrc_GetNoRootNodes(self)
    def GetNoCompounds(self): return _bbrc.Bbrc_GetNoCompounds(self)
Bbrc_swigregister = _bbrc.Bbrc_swigregister
Bbrc_swigregister(Bbrc)
cvar = _bbrc.cvar



