/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class libbbrc {
  public static void setBbrc_adjust_ub(boolean value) {
    libbbrcJNI.bbrc_adjust_ub_set(value);
  }

  public static boolean getBbrc_adjust_ub() {
    return libbbrcJNI.bbrc_adjust_ub_get();
  }

  public static void setBbrc_do_pruning(boolean value) {
    libbbrcJNI.bbrc_do_pruning_set(value);
  }

  public static boolean getBbrc_do_pruning() {
    return libbbrcJNI.bbrc_do_pruning_get();
  }

  public static void setBbrc_aromatic(boolean value) {
    libbbrcJNI.bbrc_aromatic_set(value);
  }

  public static boolean getBbrc_aromatic() {
    return libbbrcJNI.bbrc_aromatic_get();
  }

  public static void setBbrc_chisq(SWIGTYPE_p_ChisqBbrcConstraint value) {
    libbbrcJNI.bbrc_chisq_set(SWIGTYPE_p_ChisqBbrcConstraint.getCPtr(value));
  }

  public static SWIGTYPE_p_ChisqBbrcConstraint getBbrc_chisq() {
    long cPtr = libbbrcJNI.bbrc_chisq_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_ChisqBbrcConstraint(cPtr, false);
  }

  public static void setBbrc_ks(SWIGTYPE_p_KSBbrcConstraint value) {
    libbbrcJNI.bbrc_ks_set(SWIGTYPE_p_KSBbrcConstraint.getCPtr(value));
  }

  public static SWIGTYPE_p_KSBbrcConstraint getBbrc_ks() {
    long cPtr = libbbrcJNI.bbrc_ks_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_KSBbrcConstraint(cPtr, false);
  }

  public static void setBbrc_do_yaml(boolean value) {
    libbbrcJNI.bbrc_do_yaml_set(value);
  }

  public static boolean getBbrc_do_yaml() {
    return libbbrcJNI.bbrc_do_yaml_get();
  }

  public static void setBbrc_gsp_out(boolean value) {
    libbbrcJNI.bbrc_gsp_out_set(value);
  }

  public static boolean getBbrc_gsp_out() {
    return libbbrcJNI.bbrc_gsp_out_get();
  }

  public static void setBbrc_bbrc_sep(boolean value) {
    libbbrcJNI.bbrc_bbrc_sep_set(value);
  }

  public static boolean getBbrc_bbrc_sep() {
    return libbbrcJNI.bbrc_bbrc_sep_get();
  }

  public static void setBbrc_regression(boolean value) {
    libbbrcJNI.bbrc_regression_set(value);
  }

  public static boolean getBbrc_regression() {
    return libbbrcJNI.bbrc_regression_get();
  }

  public static void setBbrc_db_built(boolean value) {
    libbbrcJNI.bbrc_db_built_set(value);
  }

  public static boolean getBbrc_db_built() {
    return libbbrcJNI.bbrc_db_built_get();
  }

}
