/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class libbbrcJNI {
  public final static native long new_SVector__SWIG_0();
  public final static native long new_SVector__SWIG_1(long jarg1);
  public final static native long SVector_size(long jarg1, SVector jarg1_);
  public final static native long SVector_capacity(long jarg1, SVector jarg1_);
  public final static native void SVector_reserve(long jarg1, SVector jarg1_, long jarg2);
  public final static native boolean SVector_isEmpty(long jarg1, SVector jarg1_);
  public final static native void SVector_clear(long jarg1, SVector jarg1_);
  public final static native void SVector_add(long jarg1, SVector jarg1_, String jarg2);
  public final static native String SVector_get(long jarg1, SVector jarg1_, int jarg2);
  public final static native void SVector_set(long jarg1, SVector jarg1_, int jarg2, String jarg3);
  public final static native void delete_SVector(long jarg1);
  public final static native void adjust_ub_set(boolean jarg1);
  public final static native boolean adjust_ub_get();
  public final static native void do_pruning_set(boolean jarg1);
  public final static native boolean do_pruning_get();
  public final static native void aromatic_set(boolean jarg1);
  public final static native boolean aromatic_get();
  public final static native void chisq_set(long jarg1);
  public final static native long chisq_get();
  public final static native void ks_set(long jarg1);
  public final static native long ks_get();
  public final static native void do_yaml_set(boolean jarg1);
  public final static native boolean do_yaml_get();
  public final static native void gsp_out_set(boolean jarg1);
  public final static native boolean gsp_out_get();
  public final static native void bbrc_sep_set(boolean jarg1);
  public final static native boolean bbrc_sep_get();
  public final static native void regression_set(boolean jarg1);
  public final static native boolean regression_get();
  public final static native long new_Bbrc__SWIG_0();
  public final static native long new_Bbrc__SWIG_1(int jarg1, long jarg2);
  public final static native long new_Bbrc__SWIG_2(int jarg1, long jarg2, float jarg3, boolean jarg4);
  public final static native void delete_Bbrc(long jarg1);
  public final static native void Bbrc_Reset(long jarg1, Bbrc jarg1_);
  public final static native void Bbrc_Defaults(long jarg1, Bbrc jarg1_);
  public final static native int Bbrc_GetMinfreq(long jarg1, Bbrc jarg1_);
  public final static native int Bbrc_GetType(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetBackbone(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetDynamicUpperBound(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetPruning(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetConsoleOut(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetAromatic(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetRefineSingles(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetDoOutput(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetBbrcSep(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetChisqActive(long jarg1, Bbrc jarg1_);
  public final static native float Bbrc_GetChisqSig(long jarg1, Bbrc jarg1_);
  public final static native boolean Bbrc_GetRegression(long jarg1, Bbrc jarg1_);
  public final static native void Bbrc_SetMinfreq(long jarg1, Bbrc jarg1_, int jarg2);
  public final static native boolean Bbrc_SetType(long jarg1, Bbrc jarg1_, int jarg2);
  public final static native boolean Bbrc_SetBackbone(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native boolean Bbrc_SetDynamicUpperBound(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native boolean Bbrc_SetPruning(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native boolean Bbrc_SetConsoleOut(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native void Bbrc_SetAromatic(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native boolean Bbrc_SetRefineSingles(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native void Bbrc_SetDoOutput(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native boolean Bbrc_SetBbrcSep(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native boolean Bbrc_SetChisqActive(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native boolean Bbrc_SetChisqSig(long jarg1, Bbrc jarg1_, float jarg2);
  public final static native boolean Bbrc_SetRegression(long jarg1, Bbrc jarg1_, boolean jarg2);
  public final static native long Bbrc_MineRoot(long jarg1, Bbrc jarg1_, long jarg2);
  public final static native void Bbrc_ReadGsp(long jarg1, Bbrc jarg1_, long jarg2);
  public final static native boolean Bbrc_AddCompound(long jarg1, Bbrc jarg1_, String jarg2, long jarg3);
  public final static native boolean Bbrc_AddActivity(long jarg1, Bbrc jarg1_, float jarg2, long jarg3);
  public final static native int Bbrc_GetNoRootNodes(long jarg1, Bbrc jarg1_);
  public final static native int Bbrc_GetNoCompounds(long jarg1, Bbrc jarg1_);
}
