libbbrc: bbrc.cpp File Reference
bbrc.cpp File Reference
#include "bbrc.h"
#include "globals.h"
Functions
Fminer * create0 ()
Fminer * create2 (int _type, unsigned int _minfreq)
Fminer * create4 (int _type, unsigned int _minfreq, float _chisq_val, bool _do_backbone)
void destroy (Fminer *f)
void usage ()
Function Documentation
Fminer* create0 ()
References Bbrc::Bbrc().
{
    return new Bbrc();
}
Fminer* create2 (int _type, unsigned int _minfreq)
References Bbrc::Bbrc().
{
    return new Bbrc(_type, _minfreq);
}
Fminer* create4 (int _type, unsigned int _minfreq, float _chisq_val, bool _do_backbone)
References Bbrc::Bbrc().
{
    return new Bbrc(_type, _minfreq, _chisq_val, _do_backbone);
}
void destroy (Fminer * f)
{
    delete f;
}
void usage ()
{
    cerr << endl;
    cerr << "Options for Usage 1 (BBRC mining using dynamic upper bound pruning): " << endl;
    cerr << "       [-f minfreq] [-l type] [-s] [-a] [-o] [-n] [-g] [-d [-b [-r] | -b [-u] ] ] [-p p_value]" << endl;
    cerr << endl;
    cerr << "Options for Usage 2 (Frequent subgraph mining): " << endl;
    cerr << "       [-f minfreq] [-l type] [-s] [-a] [-o] [-n] [-r]" << endl;
    cerr << endl;
}