# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_last', [dirname(__file__)])
        except ImportError:
            import _last
            return _last
        if fp is not None:
            try:
                _mod = imp.load_module('_last', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _last = swig_import_helper()
    del swig_import_helper
else:
    import _last
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _last.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _last.SwigPyIterator_value(self)
    def incr(self, n=1): return _last.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _last.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _last.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _last.SwigPyIterator_equal(self, *args)
    def copy(self): return _last.SwigPyIterator_copy(self)
    def next(self): return _last.SwigPyIterator_next(self)
    def __next__(self): return _last.SwigPyIterator___next__(self)
    def previous(self): return _last.SwigPyIterator_previous(self)
    def advance(self, *args): return _last.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _last.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _last.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _last.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _last.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _last.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _last.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _last.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class SVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _last.SVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _last.SVector___nonzero__(self)
    def __bool__(self): return _last.SVector___bool__(self)
    def __len__(self): return _last.SVector___len__(self)
    def pop(self): return _last.SVector_pop(self)
    def __getslice__(self, *args): return _last.SVector___getslice__(self, *args)
    def __setslice__(self, *args): return _last.SVector___setslice__(self, *args)
    def __delslice__(self, *args): return _last.SVector___delslice__(self, *args)
    def __delitem__(self, *args): return _last.SVector___delitem__(self, *args)
    def __getitem__(self, *args): return _last.SVector___getitem__(self, *args)
    def __setitem__(self, *args): return _last.SVector___setitem__(self, *args)
    def append(self, *args): return _last.SVector_append(self, *args)
    def empty(self): return _last.SVector_empty(self)
    def size(self): return _last.SVector_size(self)
    def clear(self): return _last.SVector_clear(self)
    def swap(self, *args): return _last.SVector_swap(self, *args)
    def get_allocator(self): return _last.SVector_get_allocator(self)
    def begin(self): return _last.SVector_begin(self)
    def end(self): return _last.SVector_end(self)
    def rbegin(self): return _last.SVector_rbegin(self)
    def rend(self): return _last.SVector_rend(self)
    def pop_back(self): return _last.SVector_pop_back(self)
    def erase(self, *args): return _last.SVector_erase(self, *args)
    def __init__(self, *args): 
        this = _last.new_SVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _last.SVector_push_back(self, *args)
    def front(self): return _last.SVector_front(self)
    def back(self): return _last.SVector_back(self)
    def assign(self, *args): return _last.SVector_assign(self, *args)
    def resize(self, *args): return _last.SVector_resize(self, *args)
    def insert(self, *args): return _last.SVector_insert(self, *args)
    def reserve(self, *args): return _last.SVector_reserve(self, *args)
    def capacity(self): return _last.SVector_capacity(self)
    __swig_destroy__ = _last.delete_SVector
    __del__ = lambda self : None;
SVector_swigregister = _last.SVector_swigregister
SVector_swigregister(SVector)

class Last(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Last, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Last, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _last.new_Last()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _last.delete_Last
    __del__ = lambda self : None;
    def Reset(self): return _last.Last_Reset(self)
    def Defaults(self): return _last.Last_Defaults(self)
    def GetMinfreq(self): return _last.Last_GetMinfreq(self)
    def GetType(self): return _last.Last_GetType(self)
    def GetBackbone(self): return _last.Last_GetBackbone(self)
    def GetDynamicUpperBound(self): return _last.Last_GetDynamicUpperBound(self)
    def GetPruning(self): return _last.Last_GetPruning(self)
    def GetConsoleOut(self): return _last.Last_GetConsoleOut(self)
    def GetAromatic(self): return _last.Last_GetAromatic(self)
    def GetRefineSingles(self): return _last.Last_GetRefineSingles(self)
    def GetDoOutput(self): return _last.Last_GetDoOutput(self)
    def GetBbrcSep(self): return _last.Last_GetBbrcSep(self)
    def GetChisqActive(self): return _last.Last_GetChisqActive(self)
    def GetChisqSig(self): return _last.Last_GetChisqSig(self)
    def GetRegression(self): return _last.Last_GetRegression(self)
    def GetMaxHops(self): return _last.Last_GetMaxHops(self)
    def SetMinfreq(self, *args): return _last.Last_SetMinfreq(self, *args)
    def SetType(self, *args): return _last.Last_SetType(self, *args)
    def SetBackbone(self, *args): return _last.Last_SetBackbone(self, *args)
    def SetDynamicUpperBound(self, *args): return _last.Last_SetDynamicUpperBound(self, *args)
    def SetPruning(self, *args): return _last.Last_SetPruning(self, *args)
    def SetConsoleOut(self, *args): return _last.Last_SetConsoleOut(self, *args)
    def SetAromatic(self, *args): return _last.Last_SetAromatic(self, *args)
    def SetRefineSingles(self, *args): return _last.Last_SetRefineSingles(self, *args)
    def SetDoOutput(self, *args): return _last.Last_SetDoOutput(self, *args)
    def SetBbrcSep(self, *args): return _last.Last_SetBbrcSep(self, *args)
    def SetChisqActive(self, *args): return _last.Last_SetChisqActive(self, *args)
    def SetChisqSig(self, *args): return _last.Last_SetChisqSig(self, *args)
    def SetRegression(self, *args): return _last.Last_SetRegression(self, *args)
    def SetMaxHops(self, *args): return _last.Last_SetMaxHops(self, *args)
    def MineRoot(self, *args): return _last.Last_MineRoot(self, *args)
    def ReadGsp(self, *args): return _last.Last_ReadGsp(self, *args)
    def AddCompound(self, *args): return _last.Last_AddCompound(self, *args)
    def AddActivity(self, *args): return _last.Last_AddActivity(self, *args)
    def GetNoRootNodes(self): return _last.Last_GetNoRootNodes(self)
    def GetNoCompounds(self): return _last.Last_GetNoCompounds(self)
    def ChisqTest(self, *args): return _last.Last_ChisqTest(self, *args)
    def KSTest(self, *args): return _last.Last_KSTest(self, *args)
Last_swigregister = _last.Last_swigregister
Last_swigregister(Last)
cvar = _last.cvar

# This file is compatible with both classic and new-style classes.


