# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.33
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _liblast
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class PySwigIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PySwigIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PySwigIterator, name)
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _liblast.delete_PySwigIterator
    __del__ = lambda self : None;
    def value(*args): return _liblast.PySwigIterator_value(*args)
    def incr(*args): return _liblast.PySwigIterator_incr(*args)
    def decr(*args): return _liblast.PySwigIterator_decr(*args)
    def distance(*args): return _liblast.PySwigIterator_distance(*args)
    def equal(*args): return _liblast.PySwigIterator_equal(*args)
    def copy(*args): return _liblast.PySwigIterator_copy(*args)
    def next(*args): return _liblast.PySwigIterator_next(*args)
    def previous(*args): return _liblast.PySwigIterator_previous(*args)
    def advance(*args): return _liblast.PySwigIterator_advance(*args)
    def __eq__(*args): return _liblast.PySwigIterator___eq__(*args)
    def __ne__(*args): return _liblast.PySwigIterator___ne__(*args)
    def __iadd__(*args): return _liblast.PySwigIterator___iadd__(*args)
    def __isub__(*args): return _liblast.PySwigIterator___isub__(*args)
    def __add__(*args): return _liblast.PySwigIterator___add__(*args)
    def __sub__(*args): return _liblast.PySwigIterator___sub__(*args)
    def __iter__(self): return self
PySwigIterator_swigregister = _liblast.PySwigIterator_swigregister
PySwigIterator_swigregister(PySwigIterator)

class SVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SVector, name)
    __repr__ = _swig_repr
    def iterator(*args): return _liblast.SVector_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _liblast.SVector___nonzero__(*args)
    def __len__(*args): return _liblast.SVector___len__(*args)
    def pop(*args): return _liblast.SVector_pop(*args)
    def __getslice__(*args): return _liblast.SVector___getslice__(*args)
    def __setslice__(*args): return _liblast.SVector___setslice__(*args)
    def __delslice__(*args): return _liblast.SVector___delslice__(*args)
    def __delitem__(*args): return _liblast.SVector___delitem__(*args)
    def __getitem__(*args): return _liblast.SVector___getitem__(*args)
    def __setitem__(*args): return _liblast.SVector___setitem__(*args)
    def append(*args): return _liblast.SVector_append(*args)
    def empty(*args): return _liblast.SVector_empty(*args)
    def size(*args): return _liblast.SVector_size(*args)
    def clear(*args): return _liblast.SVector_clear(*args)
    def swap(*args): return _liblast.SVector_swap(*args)
    def get_allocator(*args): return _liblast.SVector_get_allocator(*args)
    def begin(*args): return _liblast.SVector_begin(*args)
    def end(*args): return _liblast.SVector_end(*args)
    def rbegin(*args): return _liblast.SVector_rbegin(*args)
    def rend(*args): return _liblast.SVector_rend(*args)
    def pop_back(*args): return _liblast.SVector_pop_back(*args)
    def erase(*args): return _liblast.SVector_erase(*args)
    def __init__(self, *args): 
        this = _liblast.new_SVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _liblast.SVector_push_back(*args)
    def front(*args): return _liblast.SVector_front(*args)
    def back(*args): return _liblast.SVector_back(*args)
    def assign(*args): return _liblast.SVector_assign(*args)
    def resize(*args): return _liblast.SVector_resize(*args)
    def insert(*args): return _liblast.SVector_insert(*args)
    def reserve(*args): return _liblast.SVector_reserve(*args)
    def capacity(*args): return _liblast.SVector_capacity(*args)
    __swig_destroy__ = _liblast.delete_SVector
    __del__ = lambda self : None;
SVector_swigregister = _liblast.SVector_swigregister
SVector_swigregister(SVector)

class Last(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Last, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Last, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _liblast.new_Last(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _liblast.delete_Last
    __del__ = lambda self : None;
    def Reset(*args): return _liblast.Last_Reset(*args)
    def Defaults(*args): return _liblast.Last_Defaults(*args)
    def GetMinfreq(*args): return _liblast.Last_GetMinfreq(*args)
    def GetType(*args): return _liblast.Last_GetType(*args)
    def GetBackbone(*args): return _liblast.Last_GetBackbone(*args)
    def GetDynamicUpperBound(*args): return _liblast.Last_GetDynamicUpperBound(*args)
    def GetPruning(*args): return _liblast.Last_GetPruning(*args)
    def GetConsoleOut(*args): return _liblast.Last_GetConsoleOut(*args)
    def GetAromatic(*args): return _liblast.Last_GetAromatic(*args)
    def GetRefineSingles(*args): return _liblast.Last_GetRefineSingles(*args)
    def GetDoOutput(*args): return _liblast.Last_GetDoOutput(*args)
    def GetBbrcSep(*args): return _liblast.Last_GetBbrcSep(*args)
    def GetChisqActive(*args): return _liblast.Last_GetChisqActive(*args)
    def GetChisqSig(*args): return _liblast.Last_GetChisqSig(*args)
    def GetRegression(*args): return _liblast.Last_GetRegression(*args)
    def GetMaxHops(*args): return _liblast.Last_GetMaxHops(*args)
    def SetMinfreq(*args): return _liblast.Last_SetMinfreq(*args)
    def SetType(*args): return _liblast.Last_SetType(*args)
    def SetBackbone(*args): return _liblast.Last_SetBackbone(*args)
    def SetDynamicUpperBound(*args): return _liblast.Last_SetDynamicUpperBound(*args)
    def SetPruning(*args): return _liblast.Last_SetPruning(*args)
    def SetConsoleOut(*args): return _liblast.Last_SetConsoleOut(*args)
    def SetAromatic(*args): return _liblast.Last_SetAromatic(*args)
    def SetRefineSingles(*args): return _liblast.Last_SetRefineSingles(*args)
    def SetDoOutput(*args): return _liblast.Last_SetDoOutput(*args)
    def SetBbrcSep(*args): return _liblast.Last_SetBbrcSep(*args)
    def SetChisqActive(*args): return _liblast.Last_SetChisqActive(*args)
    def SetChisqSig(*args): return _liblast.Last_SetChisqSig(*args)
    def SetRegression(*args): return _liblast.Last_SetRegression(*args)
    def SetMaxHops(*args): return _liblast.Last_SetMaxHops(*args)
    def MineRoot(*args): return _liblast.Last_MineRoot(*args)
    def ReadGsp(*args): return _liblast.Last_ReadGsp(*args)
    def AddCompound(*args): return _liblast.Last_AddCompound(*args)
    def AddActivity(*args): return _liblast.Last_AddActivity(*args)
    def GetNoRootNodes(*args): return _liblast.Last_GetNoRootNodes(*args)
    def GetNoCompounds(*args): return _liblast.Last_GetNoCompounds(*args)
Last_swigregister = _liblast.Last_swigregister
Last_swigregister(Last)
cvar = _liblast.cvar



