/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class liblastJNI {
  public final static native long new_SVector__SWIG_0();
  public final static native long new_SVector__SWIG_1(long jarg1);
  public final static native long SVector_size(long jarg1, SVector jarg1_);
  public final static native long SVector_capacity(long jarg1, SVector jarg1_);
  public final static native void SVector_reserve(long jarg1, SVector jarg1_, long jarg2);
  public final static native boolean SVector_isEmpty(long jarg1, SVector jarg1_);
  public final static native void SVector_clear(long jarg1, SVector jarg1_);
  public final static native void SVector_add(long jarg1, SVector jarg1_, String jarg2);
  public final static native String SVector_get(long jarg1, SVector jarg1_, int jarg2);
  public final static native void SVector_set(long jarg1, SVector jarg1_, int jarg2, String jarg3);
  public final static native void delete_SVector(long jarg1);
  public final static native void last_do_pruning_set(boolean jarg1);
  public final static native boolean last_do_pruning_get();
  public final static native void last_aromatic_set(boolean jarg1);
  public final static native boolean last_aromatic_get();
  public final static native void last_chisq_set(long jarg1);
  public final static native long last_chisq_get();
  public final static native void last_ks_set(long jarg1);
  public final static native long last_ks_get();
  public final static native void last_gsp_out_set(boolean jarg1);
  public final static native boolean last_gsp_out_get();
  public final static native void last_bbrc_sep_set(boolean jarg1);
  public final static native boolean last_bbrc_sep_get();
  public final static native void last_regression_set(boolean jarg1);
  public final static native boolean last_regression_get();
  public final static native void last_max_hops_set(int jarg1);
  public final static native int last_max_hops_get();
  public final static native void last_db_built_set(boolean jarg1);
  public final static native boolean last_db_built_get();
  public final static native long new_Last();
  public final static native void delete_Last(long jarg1);
  public final static native void Last_Reset(long jarg1, Last jarg1_);
  public final static native void Last_Defaults(long jarg1, Last jarg1_);
  public final static native int Last_GetMinfreq(long jarg1, Last jarg1_);
  public final static native int Last_GetType(long jarg1, Last jarg1_);
  public final static native boolean Last_GetBackbone(long jarg1, Last jarg1_);
  public final static native boolean Last_GetDynamicUpperBound(long jarg1, Last jarg1_);
  public final static native boolean Last_GetPruning(long jarg1, Last jarg1_);
  public final static native boolean Last_GetConsoleOut(long jarg1, Last jarg1_);
  public final static native boolean Last_GetAromatic(long jarg1, Last jarg1_);
  public final static native boolean Last_GetRefineSingles(long jarg1, Last jarg1_);
  public final static native boolean Last_GetDoOutput(long jarg1, Last jarg1_);
  public final static native boolean Last_GetBbrcSep(long jarg1, Last jarg1_);
  public final static native boolean Last_GetChisqActive(long jarg1, Last jarg1_);
  public final static native float Last_GetChisqSig(long jarg1, Last jarg1_);
  public final static native boolean Last_GetRegression(long jarg1, Last jarg1_);
  public final static native int Last_GetMaxHops(long jarg1, Last jarg1_);
  public final static native void Last_SetMinfreq(long jarg1, Last jarg1_, int jarg2);
  public final static native boolean Last_SetType(long jarg1, Last jarg1_, int jarg2);
  public final static native boolean Last_SetBackbone(long jarg1, Last jarg1_, boolean jarg2);
  public final static native boolean Last_SetDynamicUpperBound(long jarg1, Last jarg1_, boolean jarg2);
  public final static native boolean Last_SetPruning(long jarg1, Last jarg1_, boolean jarg2);
  public final static native boolean Last_SetConsoleOut(long jarg1, Last jarg1_, boolean jarg2);
  public final static native void Last_SetAromatic(long jarg1, Last jarg1_, boolean jarg2);
  public final static native boolean Last_SetRefineSingles(long jarg1, Last jarg1_, boolean jarg2);
  public final static native void Last_SetDoOutput(long jarg1, Last jarg1_, boolean jarg2);
  public final static native boolean Last_SetBbrcSep(long jarg1, Last jarg1_, boolean jarg2);
  public final static native boolean Last_SetChisqActive(long jarg1, Last jarg1_, boolean jarg2);
  public final static native boolean Last_SetChisqSig(long jarg1, Last jarg1_, float jarg2);
  public final static native boolean Last_SetRegression(long jarg1, Last jarg1_, boolean jarg2);
  public final static native boolean Last_SetMaxHops(long jarg1, Last jarg1_, int jarg2);
  public final static native long Last_MineRoot(long jarg1, Last jarg1_, long jarg2);
  public final static native void Last_ReadGsp(long jarg1, Last jarg1_, long jarg2);
  public final static native boolean Last_AddCompound(long jarg1, Last jarg1_, String jarg2, long jarg3);
  public final static native boolean Last_AddActivity(long jarg1, Last jarg1_, float jarg2, long jarg3);
  public final static native int Last_GetNoRootNodes(long jarg1, Last jarg1_);
  public final static native int Last_GetNoCompounds(long jarg1, Last jarg1_);
  public final static native float Last_ChisqTest(long jarg1, Last jarg1_, long jarg2, long jarg3);
  public final static native float Last_KSTest(long jarg1, Last jarg1_, long jarg2, long jarg3);
}
